aliases: {soc: Qick105}
device:
  qubit:
    T1: [60.61, 23.05, 31.37]
    T2e: [43.11, 6.81, 14.62]
    T2r: [40.69, 4.6618, 17.31]
    f_ef: [2972.7586, 4202.3503, 4814.4223]
    f_ge: [3116.623, 4423.5243, 5065.648]
    kappa: [30.2293, 1.4064, 12.4646]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0011, 0.0008, 0.0011]
    pulses:
      pi_ef:
        gain: [0.0438, 0.0316, 0.0152]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.1531, 0.1099, 0.0974]
        sigma: [0.03, 0.03, 0.03]
        sigma_inc: [4, 4, 4]
        type: [gauss, gauss, gauss]
    spec_gain: [0.1, 0.1, 0.1]
    temp: [21.9531, 29.9877, 35.8291]
    tuned_up: [true, true, true]
  readout:
    active_reset: [false, false, false]
    chi: [-0.4473, -0.607, -1.1502]
    fidelity: [0.8941, 0.8503, 0.9091]
    final_delay: [363.66, 138.28, 188.2]
    frequency: [5381.7811, 5920.7566, 6629.0562]
    gain: [0.0075, 0.0108, 0.024]
    kappa: [0.4458, 0.4845, 0.5629]
    lamb: [-1.3126, -1.7883, -3.005]
    max_gain: 1
    phase: [-86.7851, 98.9775, 60.0319]
    qe: [1.4802, 1.448, 1.4147]
    qi: [6.5428, 7.8285, 7.0275]
    readout_length: [3.75, 2.7, 3.75]
    reps: [1, 1, 1]
    reps_base: 150
    rescale: [false, false, false]
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    rounds: [1, 1, 1]
    rounds_base: 1
    sigma: [5.3377, 1.257, 1.0235]
    threshold: [15.1114, 3.3014, 3.003]
    tm: [0.0744, 0.1476, 0.1526]
    trig_offset: [0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
        type: [dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
