aliases: {soc: Qick105}
device:
  qubit:
    T1: [57.07, 23.57, 27.65]
    T2e: [19.55, 3.19, 7.57]
    T2r: [40.43, 5.11, 14.75]
    f_ef: [2972.7586, 4202.3503, 4814.4223]
    f_ge: [3116.6222, 4423.5566, 5065.6553]
    kappa: [30.2293, 1.4064, 12.4646]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0011, 0.0008, 0.0011]
    pulses:
      pi_ef:
        gain: [0.0438, 0.0316, 0.0152]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.1517, 0.1127, 0.098]
        sigma: [0.03, 0.03, 0.03]
        sigma_inc: [4, 4, 4]
        type: [gauss, gauss, gauss]
    spec_gain: [0.1, 0.1, 0.1]
    temp: [21.9531, 29.9877, 35.8291]
    tuned_up: [true, true, true]
  readout:
    active_reset: [false, false, false]
    chi: [-0.4473, -0.639, -1.2141]
    fidelity: [0.8892, 0.9151, 0.9174]
    final_delay: [342.44, 141.43, 165.88]
    frequency: [5381.7898, 5920.7411, 6629.0655]
    gain: [0.0075, 0.012, 0.024]
    kappa: [0.45, 0.5131, 0.555]
    lamb: [-1.3126, -1.7883, -3.005]
    max_gain: 1
    phase: [-1.649, 18.7392, 28.3293]
    qe: [1.5064, 1.4682, 1.4379]
    qi: [5.8042, 5.3908, 7.0546]
    readout_length: [3.75, 3.75, 3.75]
    reps: [1, 1, 1]
    reps_base: 150
    rescale: [false, false, false]
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    sigma: [1.0444, 1.0808, 1.0253]
    soft_avgs: [1, 1, 1]
    soft_avgs_base: 1
    threshold: [3.0082, 3.328, 3.078]
    tm: [0.0833, 0.1385, 0.1409]
    trig_offset: [0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
        type: [dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
