aliases: {soc: Qick105}
device:
  qubit:
    T1: [103.05, 62.76, 24.17]
    T2e: [21.68, 18.28, 20.05]
    T2r: [42.28, 25.6, 32.56]
    f_ef: [3250.0555, 4361.0968, 5298.7098]
    f_ge: [3396.5797, 4590.4932, 5567.3128]
    kappa: [0.8525, 0.224, 107.1806]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0032, 0.0064, 0.0035]
    pulses:
      pi_ef:
        gain: [0.2831, 0.5108, 0.1246]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.0217, 0.0252, 0.0138]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
    spec_gain: [0.1, 0.1, 0.8]
    temp: [28.3178, 43.5699, 46.9897]
    tuned_up: [true, true, true]
  readout:
    active_reset: [false, false, false]
    chi: [-0.3514, -0.9265, -1.7253]
    fidelity: [0.6387, 0.7415, 0.5898]
    final_delay: [618.3, 376.53, 145.0]
    frequency: [5375.7034, 5915.542, 6623.2794]
    gain: [0.0208, 0.026, 0.0653]
    kappa: [0.6002, 0.1017, 0.6268]
    lamb: [-1.7241, -2.1402, -5.2399]
    max_gain: 1
    phase: [-102.1521, 8.4278, 94.3175]
    qe: [0.9557, 9.5323, 1.5333]
    qi: [14.2338, 14.9067, 3.3997]
    readout_length: [21.1151, 26.6717, 14.704]
    reps: [1, 1, 1]
    reps_base: 200
    rescale: [false, false, false]
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    sigma: [0.8734, 0.7725, 0.8806]
    soft_avgs: [1, 1, 1]
    soft_avgs_base: 1
    threshold: [-0.1033, 1.5244, 3.2162]
    tm: [0.3765, 0.3581, 0.5843]
    trig_offset: [0.4, 0.4, 0.4]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
        type: [dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
stark:
  f: [null, null, null]
  fneg: [null, null, null]
  l: [null, null, 1.534]
  lneg: [null, null, 5.6796]
  o: [null, null, 0.1247]
  oneg: [null, null, -0.6774]
  q: [null, null, 65.236]
  qneg: [null, null, 18.6405]
