aliases: {soc: bf1_soc}
device:
  qubit:
    T1: [1.71, 1, 1]
    T2e: [60, 60, 60]
    T2r: [75, 50.78, 30]
    f_ef: [2400, 3315, 3880] # 250 / 290
    f_ge: [2517.7048, 3568.8985, 4168.7824]
    kappa: [-19.4523, 1.4088, 4.3109]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.15, 0.15, 0.15]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.005, 0.1453, 0.1]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [4, 4, 4]
        type: [gauss, gauss, gauss]
    spec_gain: [10, 10, 10]
    temp: [0, 0, 0]
    tuned_up: [true, false, false]
  readout:
    active_reset: [false, false, false]
    chi: [0, 0, 0]
    fidelity: [0.1594, 0, 0.0265]
    final_delay: [10.28, 10, 10]
    frequency: [5303.6623, 5833.7177, 6528.8395]
    gain: [0.025, 0.035, 0.05]
    kappa: [0.6804, 1.0766, 0.7454]
    lamb: [-0.6713, -0.7203, -1.3384]
    max_gain: 1
    phase: [90.0, 0, -54.487]
    qe: [1.7242, 1.2689, 1.317]
    qi: [1.4226, 0.9458, 2.6146]
    readout_length: [1.6, 1, 1]
    reps: [1, 1, 1]
    reps_base: 10000
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    sigma: [1.7348, 0, 1.4995]
    soft_avgs: [1, 1, 1]
    soft_avgs_base: 1
    threshold: [-0.1538, 10, 0.7419]
    tm: [2.038, 0, 0.1952]
    trig_offset: [0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
    dacs:
      qubit:
        ch: [3, 3, 3]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
