aliases: {soc: Qick233}
device:
  qubit:
    T1: 41.03
    T2e: 22.11
    T2r: 19.58
    f_ef: 4099.4495
    f_ge: 4273.0621
    kappa: -2.4011
    low_gain: 0.002
    max_gain: 1
    pop: 0.0008
    pulses:
      pi_ef: {gain: 0.3662, sigma: 0.05, sigma_inc: 4, type: gauss}
      pi_ge: {gain: 0.271, sigma: 0.07, sigma_inc: 4, type: gauss}
    spec_gain: 1
    temp: 28.9479
    tuned_up: true
  readout: {active_reset: false, chi: -1.438, fidelity: 0.8247, final_delay: 246.16,
    frequency: 1390.8844, gain: 0.4015, ie: 0, ig: 0, kappa: 0.6091, lamb: 0, max_gain: 1,
    phase: 164.3442, qe: 3.1888, qi: 1.4222, readout_length: 5.7845, reps: 1.2477,
    reps_base: 200, reset_e: 0.0641, reset_g: 9.44, sigma: 2.3675, rounds: 1, rounds_base: 1,
    threshold: 6.2158, tm: 0.2382, trig_offset: 0.506}
hw:
  soc:
    adcs:
      readout: {ch: 1}
    dacs:
      qubit: {ch: 1, nyquist: 2, type: full}
      readout: {ch: 3, lo_freq: 4600, nyquist: 2, type: full}
    lo: {ch: None, gain: 0, mixer_freq: 0, nyquist: None}
stark: {l: 156.5944, lneg: 19.4142, o: 88.3159, oneg: -0.6491, q: -192.6166, qneg: 987.3256}
