aliases: {soc: bf1_soc}
device:
  qubit:
    T1: [34.47, 11.41, 30]
    T2e: [8.49, 22.46, 60]
    T2r: [8.54, 5.69, 30]
    f_ef: [3827.9248, 5302.662, 3750]
    f_ge: [3963.8288, 5496.5226, 6643.4665]
    kappa: [-4.4271, 0.2632, 15.1805]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0017, 0.0371, 0]
    pulses:
      pi_ef:
        gain: [0.1819, 0.1225, 0.15]
        sigma: [0.07, 0.2, 0.1]
        sigma_inc: [5, 4, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.2658, 0.1674, 0.15]
        sigma: [0.07, 0.07, 0.1]
        sigma_inc: [5, 4, 5]
        type: [const, gauss, gauss]
    spec_gain: [1, 1, 1]
    temp: [29.7532, 80.2568, 0]
    tuned_up: [true, true, false]
  readout:
    active_reset: [false, false, false]
    chi: [-0.767, -1.9174, 0]
    fidelity: [0.7008, 0.2982, 0]
    final_delay: [206.85, 68.44, 180]
    frequency: [5379.3363, 5923.9675, 6653.3975]
    gain: [0.047, 0.0486, 0.01]
    kappa: [0.4883, 0.4549, 0.5509]
    lamb: [-3.0249, -8.9671, -4.5851]
    max_gain: 1
    phase: [-19.5688, 65.967, 0]
    qe: [1.3686, 2.1109, 2.3549]
    qi: [5.6483, 3.3994, 2.4797]
    readout_length: [11.34, 14.8837, 5]
    reps: [1, 1, 50]
    reps_base: 200
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    sigma: [8.7846, 4.9303, 0]
    soft_avgs: [1, 1, 1]
    soft_avgs_base: 1
    threshold: [13.1905, 6.158, 10]
    tm: [0.1685, 1.243, 0]
    trig_offset: [0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
    dacs:
      qubit:
        ch: [3, 3, 3]
        nyquist: [1, 1, 2]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
