aliases: {soc: Qick233}
device:
  qubit:
    T1: [30]
    T2e: [60]
    T2r: [30]
    f_ef: [3800]
    f_ge: [619.0315]
    kappa: [0.2172]
    low_gain: 0.003
    max_gain: 1
    pop: [0]
    pulses:
      pi_ef:
        gain: [0.15]
        sigma: [0.1]
        sigma_inc: [5]
        type: [gauss]
      pi_ge_flat:
        gain: [0.9797]
        length: [0.3]
        ramp_sigma: [0.02]
        ramp_sigma_inc: [4]
        type: [flat_top]
      pi_ge:
        gain: [0.7187]
        sigma: [0.3]
        sigma_inc: [5]
        type: [gauss]
    spec_gain: [40]
    temp: [0]
    tuned_up: [false]
  readout:
    active_reset: [false]
    chi: [0]
    fidelity: [0.0158]
    final_delay: [10]
    frequency: [7724.3102]
    gain: [0.006]
    kappa: [0.2892]
    lamb: [-7.4786]
    max_gain: 1
    phase: [-48.1425]
    qe: [11.0184]
    qi: [3.5251]
    readout_length: [4.32]
    reps: [1]
    reps_base: 100
    rescale: [false]
    reset_e: [0]
    reset_g: [0]
    rounds: [1]
    rounds_base: 1
    sigma: [11.4011]
    threshold: [-1.931]
    tm: [0.2]
    trig_offset: [0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [0]
        type: [dyn]
    dacs:
      qubit:
        ch: [2]
        nyquist: [1]
        type: [full]
      readout:
        ch: [0]
        nyquist: [2]
        type: [full]
stark:
  f: [null]
  fneg: [null]
  l: [null]
  lneg: [null]
  o: [null]
  oneg: [null]
  q: [null]
  qneg: [null]
