aliases: {soc: Qick233}
device:
  qubit:
    T1: [30, 30]
    T2e: [60, 60]
    T2r: [30, 30]
    f_ef: [3800, 3800]
    f_ge: [9000, 11000]
    kappa: [0, 0]
    low_gain: 0.95
    max_gain: 1
    pop: [0, 0]
    pulses:
      pi_ef:
        gain: [0.15, 0.15]
        sigma: [0.1, 0.1]
        sigma_inc: [5, 5]
        type: [gauss, gauss]
      pi_ge:
        gain: [0.15, 0.15]
        sigma: [0.1, 0.1]
        sigma_inc: [5, 5]
        type: [gauss, gauss]
    rescale: [false, false]
    spec_gain: [64, 1]
    temp: [0, 0]
    tuned_up: [false, false]
  readout:
    active_reset: [false, false]
    chi: [0, 0]
    fidelity: [0, 0]
    final_delay: [180, 180]
    frequency: [7724.2605, 7000]
    gain: [0.03, 0.05]
    kappa: [0.1938, 0.5]
    lamb: [1.0551, -0.3445]
    max_gain: 1
    phase: [0, 0]
    qe: [18.6129, 0]
    qi: [5.072, 0]
    readout_length: [5, 5]
    reps: [1, 1]
    reps_base: 300
    reset_e: [0, 0]
    reset_g: [0, 0]
    sigma: [0, 0]
    rounds: [1, 1]
    rounds_base: 1
    threshold: [10, 10]
    tm: [0, 0]
    trig_offset: [0.48177083333333337, 0.48177083333333337]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 0, 0]
        type: [dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1]
        nyquist: [2, 2, 2]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
